### ISSUE TITLE
outread error of a abinit output

### ISSUE THREAD

**Issue by mxz2013** [teoguso/SF#1]
When I use the attached file as inputs in numint2 repo, it report an error as
"  File "../../sf.py", line 70, in <module>
    gwout = AbinitOutReader(filename = out_file,is_sc = invar_dict['is_sc']) 
  File "/home/zhou/SF_Sky_git/outread/outread.py", line 449, in __init__
    self.get_gw_qpen(i,self.nversion)
  File "/home/zhou/SF_Sky_git/outread/outread.py", line 850, in get_gw_qpen
    hf_k = qpen_k - sigc_k
TypeError: unsupported operand type(s) for -: 'list' and 'list'
"
But I have checked the types of qpen_k and sigc_k, they are np.array types so "-" operation should be fine. Could you please help me figure out the reason of this error?

Thank you very much!
Sky

[HEG.tar.gz](https://github.com/teoguso/SF/files/656774/HEG.tar.gz)

**Comment by teoguso** [comment]
There was a problem in the parser for the abinit output and a mistake in how the evaluation of the version of abinit was handled. It should be now fixed.
